"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { motion, useReducedMotion } from "motion/react";
import { Award, ArrowRight, BarChart3, BriefcaseBusiness, Camera, Check, Coffee, Compass, Globe, Leaf, Mail, MapPin, Menu, MessageCircle, PenLine, Phone, Sparkles, Users, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { BrandMark } from "@/components/brand-mark";
import NavigationMenuWithActiveItem from "@/components/ui/navigation-menu-05";
import { Reveal } from "@/components/ui/reveal";
import { RevealImage } from "@/components/ui/reveal-image";
import { CountUp } from "@/components/ui/count-up";
import { Magnetic } from "@/components/ui/magnetic";
import { Marquee } from "@/components/ui/marquee";
import { ScrollProgress } from "@/components/ui/scroll-progress";

function useScrolled(threshold = 8) {
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > threshold);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, [threshold]);
  return scrolled;
}

const nav = [["Inicio", "/", true], ["Servicios", "/servicios", false], ["Proyectos", "/proyectos", false], ["Formación", "/formacion", false], ["Recursos", "/recursos", false], ["Sobre nosotros", "/sobre-nosotros", false], ["Contacto", "/contacto", false]] as const;
const pillars = [
  { title: "Creamos", label: "Damos vida a tu proyecto", icon: Sparkles, image: "/images/pillar-creamos.jpg", bullets: ["Concepto y viabilidad", "Diseño e identidad", "Carta y experiencia", "Operaciones y proveedores", "Apertura y acompañamiento"] },
  { title: "Analizamos", label: "Mejoramos tu negocio actual", icon: BarChart3, image: "/images/pillar-analizamos.jpg", bullets: ["Auditoría integral", "Análisis de producto y carta", "Costes y rentabilidad", "Procesos y eficiencia", "Experiencia del cliente"] },
  { title: "Formamos", label: "Desarrollamos tu equipo", icon: Users, image: "/images/pillar-formamos.jpg", bullets: ["Barista & Espresso", "Latte Art", "Métodos de filtrado", "Atención al cliente", "Formación a medida"] },
];
const steps = [["01", "Escuchamos", "Entendemos tu idea, tus necesidades y tus objetivos.", MessageCircle], ["02", "Analizamos", "Estudiamos el mercado, los números y el potencial.", Compass], ["03", "Diseñamos", "Creamos la estrategia, concepto y plan de acción.", PenLine], ["04", "Implementamos", "Te acompañamos en la puesta en marcha con nuestro equipo.", Coffee], ["05", "Mejoramos", "Medimos, optimizamos y crecemos juntos.", BarChart3]] as const;

function SiteHeader() {
  const [open, setOpen] = useState(false);
  const scrolled = useScrolled();
  return <header className={`sticky top-0 z-50 border-b border-black/5 bg-cream/95 backdrop-blur-md transition-shadow duration-300 ${scrolled ? "shadow-[0_2px_20px_rgba(23,23,23,.06)]" : ""}`}><div className={`mx-auto flex max-w-[1320px] items-center justify-between px-6 transition-[height] duration-300 lg:px-10 ${scrolled ? "h-[62px]" : "h-[76px]"}`}><Link href="/" className="flex items-center gap-3 leading-none" onClick={() => setOpen(false)}><BrandMark className="text-terracotta" size={34} /><span><span className="display block text-[22px]">Coffee Dreams<sup className="text-[8px]">®</sup></span><span className="ml-8 text-[10px] tracking-[.12em]">Consulting</span></span></Link><nav className="hidden items-center gap-5 lg:flex">{nav.map(([label, href, enabled]) => enabled ? <Link key={href} href={href} className="text-[9px] font-semibold uppercase tracking-[.08em] text-olive transition-colors hover:text-olive">{label}</Link> : <button key={href} type="button" className="text-[9px] font-semibold uppercase tracking-[.08em] text-ink/35 transition-colors hover:text-olive focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-terracotta">{label}</button>)}</nav><Magnetic strength={0.3} className="hidden lg:block"><button type="button" className="magnetic-btn rounded-sm bg-ink/10 px-5 py-3 text-[9px] font-semibold uppercase tracking-[.12em] text-ink/40 transition-colors hover:bg-olive hover:text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-terracotta">Hablemos</button></Magnetic><button type="button" className="lg:hidden" onClick={() => setOpen(!open)} aria-label={open ? "Cerrar menú" : "Abrir menú"}>{open ? <X size={22} /> : <Menu size={22} />}</button></div>{open && <nav className="border-t border-black/5 bg-cream px-6 py-5 lg:hidden">{nav.map(([label, href, enabled]) => enabled ? <Link key={href} href={href} onClick={() => setOpen(false)} className="block border-b border-black/10 py-3 text-xs font-semibold uppercase tracking-[.12em] text-olive">{label}</Link> : <button key={href} type="button" className="block w-full border-b border-black/10 py-3 text-left text-xs font-semibold uppercase tracking-[.12em] text-ink/35 transition-colors hover:text-olive focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-terracotta">{label}</button>)}</nav>}</header>;
}

function NavigationHeader() {
  const [open, setOpen] = useState(false);
  const scrolled = useScrolled();
  return <header className={`sticky top-0 z-50 border-b border-black/5 bg-cream/95 backdrop-blur-md transition-shadow duration-300 ${scrolled ? "shadow-[0_2px_20px_rgba(23,23,23,.06)]" : ""}`}><div className={`mx-auto flex max-w-[1320px] items-center justify-between px-6 transition-[height] duration-300 lg:px-10 ${scrolled ? "h-[62px]" : "h-[76px]"}`}><Link href="/" className="flex items-center gap-3 leading-none" onClick={() => setOpen(false)}><BrandMark className="text-terracotta" size={34} /><span><span className="display block text-[22px]">Coffee Dreams<sup className="text-[8px]">®</sup></span><span className="ml-8 text-[10px] tracking-[.12em]">Consulting</span></span></Link><div className="hidden lg:block"><NavigationMenuWithActiveItem /></div><Magnetic strength={0.3} className="hidden lg:block"><button type="button" className="magnetic-btn rounded-sm bg-ink/10 px-5 py-3 text-[9px] font-semibold uppercase tracking-[.12em] text-ink/40 transition-colors hover:bg-olive hover:text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-terracotta">Hablemos</button></Magnetic><button type="button" className="lg:hidden" onClick={() => setOpen(!open)} aria-label={open ? "Cerrar menú" : "Abrir menú"}>{open ? <X size={22} /> : <Menu size={22} />}</button></div>{open && <nav className="border-t border-black/5 bg-cream px-6 py-5 lg:hidden">{nav.map(([label, href, enabled]) => enabled ? <Link key={href} href={href} onClick={() => setOpen(false)} className="block border-b border-black/10 py-3 text-xs font-semibold uppercase tracking-[.12em] text-olive">{label}</Link> : <button key={href} type="button" className="block w-full border-b border-black/10 py-3 text-left text-xs font-semibold uppercase tracking-[.12em] text-ink/35 transition-colors hover:text-olive focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-terracotta">{label}</button>)}</nav>}</header>;
}

function Hero() { return <section className="relative overflow-hidden bg-cream"><div className="relative mx-auto grid max-w-[1320px] bg-none max-lg:bg-[url('/images/hero-cafe3.jpg')] max-lg:bg-cover max-lg:bg-[position:82%_70%] lg:min-h-[610px] lg:grid-cols-[.86fr_1.14fr] lg:bg-[url('/images/hero-cafe3.jpg')] lg:bg-[length:90%_auto] lg:bg-[position:right_70%] lg:bg-no-repeat lg:before:absolute lg:before:inset-y-0 lg:before:left-0 lg:before:z-[1] lg:before:w-[54%] lg:before:bg-gradient-to-r lg:before:from-cream lg:before:via-cream/95 lg:before:to-transparent lg:before:content-['']"><div className="relative z-10 flex flex-col justify-center max-lg:bg-gradient-to-b max-lg:from-cream/95 max-lg:via-cream/75 max-lg:to-cream/20 px-6 py-16 sm:px-10 lg:bg-transparent lg:px-14 lg:py-24"><p className="eyebrow mb-6 text-terracotta rise-in">Coffee Dreams Consulting</p><h1 className="display max-w-[600px] text-[42px] leading-[1.03] tracking-[-.025em] sm:text-[56px] lg:text-[64px] rise-in rise-delay-1">Creamos, analizamos y formamos para negocios de <em className="text-terracotta not-italic">café</em></h1><p className="mt-7 max-w-[410px] text-[13px] leading-7 text-ink/70 rise-in rise-delay-2">Te acompañamos en cada etapa de tu proyecto o negocio: desde la idea hasta la mejora continua. Más rentabilidad, mejor experiencia, mayor propósito.</p><Magnetic strength={0.25} className="mt-8 w-fit rise-in rise-delay-3"><Link href="/contacto" className="magnetic-btn group inline-flex w-fit items-center gap-4 bg-terracotta px-6 py-4 text-[10px] font-semibold uppercase tracking-[.12em] text-white transition-colors hover:bg-terracotta/80">Cuéntanos tu proyecto <ArrowRight size={15} className="transition-transform duration-300 group-hover:translate-x-1" /></Link></Magnetic><p className="mt-9 flex items-center gap-2 text-[10px] text-olive"><Leaf size={18} /> Pasión por el café. Visión de negocio.</p></div><div className="relative max-lg:hidden min-h-[300px] overflow-hidden sm:min-h-[360px] lg:-ml-20 lg:block lg:min-h-full"><div className="absolute inset-0 hidden"/><div className="absolute inset-0 bg-gradient-to-r from-transparent via-transparent to-ink/10"/></div></div></section>; }

function Pillars() { return <section className="bg-cream"><div className="mx-auto max-w-[1320px] px-6 pb-16 pt-8 lg:px-10 lg:pt-10"><Reveal className="mb-8 flex items-end justify-between"><div><p className="eyebrow text-terracotta">Lo que hacemos</p><h2 className="display mt-3 text-4xl">Tres formas de hacer crecer tu café.</h2></div><p className="hidden max-w-[250px] text-right text-xs leading-6 text-ink/60 md:block">Estrategia, creatividad y oficio para construir negocios con alma.</p></Reveal><div className="grid overflow-hidden rounded-[22px] border border-black/10 md:grid-cols-3">{pillars.map(({ title, label, icon: Icon, bullets, image }, index) => <Reveal key={title} index={index}><article className={`group relative min-h-[470px] overflow-hidden p-8 ${index === 1 ? "bg-olive text-cream" : "bg-sand/25"}`}><div className="absolute inset-0 bg-cover bg-center opacity-25 mix-blend-multiply transition duration-700 group-hover:scale-105 group-hover:opacity-35" style={{ backgroundImage: `url(${image})` }} /><div className="absolute inset-0 bg-gradient-to-t from-ink/15 via-transparent to-cream/10" /><div className="relative flex h-full flex-col"><div className="icon-badge mb-8 flex h-16 w-16 items-center justify-center rounded-full border-2 border-cream bg-cream text-olive"><Icon size={27} /></div><h3 className="display text-4xl">{title}</h3><p className="mt-2 text-xs font-semibold uppercase tracking-[.08em] text-terracotta">{label}</p><ul className="mt-8 space-y-3 text-[11px] leading-5 opacity-80">{bullets.map((bullet) => <li key={bullet} className="flex gap-2"><Check size={14} className="mt-0.5 shrink-0" />{bullet}</li>)}</ul><Link href="/servicios" className="mt-auto flex items-center gap-2 pt-8 text-[10px] font-semibold uppercase tracking-[.12em]">Saber más <ArrowRight size={14} className="transition-transform duration-300 group-hover:translate-x-1" /></Link></div></article></Reveal>)}</div></div></section>; }

const stats: [number, string, string, string, LucideIcon][] = [[15, "+", "", "Años de experiencia", Award], [60, "+", "", "Proyectos realizados", BarChart3], [200, "+", "", "Profesionales formados", Users], [100, "", "%", "Comprometidos", Coffee]];

function Stats() { return <section className="grain bg-olive-deep text-cream"><div className="mx-auto grid max-w-[1320px] items-center gap-10 px-6 py-14 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><Reveal><p className="eyebrow text-sand">La medida de nuestro trabajo</p><h2 className="display mt-4 text-4xl leading-tight">El café se disfruta.<br /><span className="text-sand">El negocio se diseña.</span></h2></Reveal><div className="grid grid-cols-2 gap-y-8 sm:grid-cols-4">{stats.map(([value, prefix, suffix, label, Icon], index) => <Reveal key={label} index={index} className="border-l border-cream/20 pl-5"><Icon size={29} className="stat-icon mb-4 text-sand" aria-hidden="true" /><p className="display flex items-baseline text-4xl text-sand">{prefix}<CountUp to={value} duration={1.25} digitEffect="none" /><span>{suffix}</span></p><p className="mt-2 max-w-[110px] text-[9px] font-semibold uppercase leading-4 tracking-[.08em] text-cream/70">{label}</p></Reveal>)}</div></div></section>; }

function Process() {
  const reduceMotion = useReducedMotion();
  return <section className="bg-cream px-6 py-14 lg:px-10 lg:py-20"><div className="mx-auto max-w-[1150px]"><Reveal className="text-center"><p className="eyebrow text-terracotta">Nuestro proceso</p><h2 className="display mt-3 text-4xl">Un camino claro hacia el éxito</h2></Reveal><div className="relative mt-10 grid gap-8 md:mt-16 md:grid-cols-5 md:gap-5">{steps.map(([number, title, text, Icon], index) => <Reveal key={number} index={index} className="relative text-center"><div className="process-icon mx-auto flex h-[68px] w-[68px] items-center justify-center rounded-full border-2 border-terracotta/55 bg-cream text-olive"><Icon size={27} /></div><span className="mt-4 block text-[9px] font-semibold tracking-[.16em] text-terracotta">{number}</span><h3 className="mt-2 text-[11px] font-semibold uppercase tracking-[.08em]">{title}</h3><p className="mx-auto mt-3 max-w-[160px] text-[11px] leading-5 text-ink/60">{text}</p>{index < steps.length - 1 && <motion.span initial={{ scaleX: 0 }} whileInView={{ scaleX: 1, transition: reduceMotion ? { duration: 0 } : { duration: 0.9, delay: index * 0.15 + 0.2, ease: [0.22, 1, 0.36, 1] } }} viewport={{ once: true, amount: 0.6 }} style={{ transformOrigin: "left" }} className="absolute left-[calc(50%+42px)] right-[calc(-50%-42px)] top-8 hidden h-px bg-terracotta/40 md:block" />}</Reveal>)}</div></div></section>;
}

function Projects() { return <section className="grain bg-ink px-6 py-20 text-cream lg:px-10"><div className="mx-auto grid max-w-[1320px] gap-10 lg:grid-cols-[.95fr_1.05fr]"><div className="min-h-[420px] overflow-hidden rounded-[20px]"><RevealImage src="/images/idea.jpg" className="h-full min-h-[420px] transition-transform duration-700 hover:scale-105" /></div><Reveal index={1} className="flex flex-col justify-center"><p className="eyebrow text-sand">Proyectos que inspiran</p><h2 className="display mt-4 max-w-[510px] text-5xl leading-[1.05]">Ideas que se convierten <span className="text-sand">en experiencias.</span></h2><p className="mt-6 max-w-[460px] text-sm leading-7 text-cream/65">Desde el concepto hasta la última taza, hacemos que cada detalle cuente. Una mirada estratégica con sensibilidad por lo que hace especial a un lugar.</p><Link href="/proyectos" className="group mt-8 flex w-fit items-center gap-3 text-[10px] font-semibold uppercase tracking-[.13em] text-sand">Ver proyectos <ArrowRight size={15} className="transition-transform duration-300 group-hover:translate-x-1" /></Link><div className="mt-12 grid grid-cols-3 gap-3">{[["Diseño y apertura", "/images/proyecto-diseno-apertura.jpg"], ["Análisis y optimización", "/images/proyecto-analisis-optimizacion.jpg"], ["Formación", "/images/latteart.jpg"]].map(([label, image], i) => <div key={label} className="group"><div className="aspect-square overflow-hidden rounded-lg"><RevealImage src={image} index={i + 2} className="h-full w-full transition-transform duration-500 group-hover:scale-110" /></div><p className="mt-2 text-[9px] uppercase leading-4 tracking-[.08em] text-sand">{label}</p></div>)}</div></Reveal></div></section>; }

const trustLogos = [
  <span key="1" className="display px-10 text-xl text-olive/80">CAFÉ NORTE</span>,
  <span key="2" className="px-10 text-xl font-semibold tracking-[.14em] text-olive/80">MAMBÚ</span>,
  <span key="3" className="display px-10 text-xl font-semibold text-olive/80">TEMPO</span>,
  <span key="4" className="px-10 text-xl font-semibold tracking-[.14em] text-olive/80">QAPHI</span>,
  <span key="5" className="display px-10 text-xl font-semibold text-olive/80">HONEY</span>,
];

function Trust() { return <section className="bg-cream py-12"><div className="mx-auto max-w-[1320px] px-6 lg:px-10"><Reveal><p className="eyebrow text-center text-terracotta">Con la confianza de</p></Reveal></div><div className="mt-8"><Marquee durationSeconds={26}>{trustLogos}</Marquee></div></section>; }

function Newsletter() { return <section className="bg-sand px-6 py-16 lg:px-10"><Reveal className="mx-auto flex max-w-[1050px] flex-col items-start justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow text-olive">Inspiración y recursos</p><h2 className="display mt-3 text-4xl">Ideas para hacer crecer<br />tu negocio de café.</h2></div><form className="flex w-full max-w-[390px] border-b border-ink/40 pb-2 transition-colors focus-within:border-terracotta" onSubmit={(event) => event.preventDefault()}><label className="sr-only" htmlFor="newsletter">Tu email</label><input id="newsletter" type="email" placeholder="Tu email" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-ink/55" required /><button className="group flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.12em]" type="submit">Suscribirme <ArrowRight size={14} className="transition-transform duration-300 group-hover:translate-x-1" /></button></form></Reveal></section>; }

function Footer() { return <footer className="grain bg-olive-deep px-6 py-14 text-cream lg:px-10"><div className="mx-auto grid max-w-[1320px] gap-10 md:grid-cols-[1.4fr_.7fr_.9fr] md:gap-20"><div><Link href="/" className="flex items-center gap-3"><BrandMark className="text-terracotta" size={42} /><span className="display text-2xl">Coffee Dreams<sup className="text-[8px]">®</sup></span></Link><p className="mt-5 max-w-[260px] text-xs leading-6 text-cream/65">Consultoría, análisis y formación para negocios de café y hostelería.</p><p className="mt-8 text-[10px] uppercase tracking-[.1em] text-sand">Pasión por el café. Visión de negocio.</p><div className="mt-7 flex items-center gap-4"><a href="https://instagram.com" aria-label="Instagram" className="text-cream/70 transition-colors hover:text-terracotta"><Camera size={18} /></a><a href="https://linkedin.com" aria-label="LinkedIn" className="text-cream/70 transition-colors hover:text-terracotta"><BriefcaseBusiness size={18} /></a><a href="https://facebook.com" aria-label="Facebook" className="text-cream/70 transition-colors hover:text-terracotta"><Globe size={18} /></a></div></div><div><p className="eyebrow text-sand">Enlaces rápidos</p><div className="mt-5 grid gap-3 text-xs text-cream/70">{nav.slice(1, 6).map(([label, href]) => <Link key={href} href={href} className="transition-colors hover:text-sand">{label}</Link>)}</div></div><div><p className="eyebrow text-sand">Hablemos</p><div className="mt-5 grid gap-3 text-xs text-cream/70"><a className="flex items-center gap-2" href="mailto:hola@coffeedreams.es"><Mail size={15} /> hola@coffeedreams.es</a><a className="flex items-center gap-2" href="tel:+34961234567"><Phone size={15} /> +34 961 234 567</a><span className="flex items-center gap-2"><MapPin size={15} /> Alicante, España</span></div></div></div><div className="mx-auto mt-12 flex max-w-[1320px] items-center justify-between border-t border-cream/15 pt-5 text-[10px] text-cream/45"><span>© 2025 Coffee Dreams Consulting. Todos los derechos reservados.</span><BrandMark className="text-terracotta" size={30} label="" /></div></footer>; }

export function CoffeeDreamsHome() { return <><ScrollProgress /><NavigationHeader /><main><Hero /><Pillars /><Stats /><Process /><Projects /><Trust /><Newsletter /></main><Footer /></>; }

const pageCopy: Record<string, { eyebrow: string; title: string; text: string; image: string }> = {
  servicios: { eyebrow: "Servicios", title: "Una mirada completa para un negocio con futuro.", text: "Aterrizamos conceptos, ordenamos operaciones y construimos experiencias de café que funcionan en el mundo real.", image: "/images/interior-servicios.jpg" },
  proyectos: { eyebrow: "Proyectos", title: "Lugares con identidad. Negocios con dirección.", text: "Una selección de aperturas, reposicionamientos y estrategias que convierten una buena idea en un lugar al que quieres volver.", image: "/images/interior-proyectos.jpg" },
  formacion: { eyebrow: "Formación", title: "El equipo es el ingrediente que lo cambia todo.", text: "Programas prácticos para elevar la técnica, la hospitalidad y la confianza de las personas que están detrás de cada barra.", image: "/images/interior-formacion.jpg" },
  recursos: { eyebrow: "Recursos", title: "Ideas para mirar tu café con otros ojos.", text: "Notas, herramientas y conversaciones para tomar mejores decisiones y disfrutar más del camino.", image: "/images/interior-recursos.jpg" },
  "sobre-nosotros": { eyebrow: "Sobre nosotros", title: "Café, criterio y ganas de hacerlo bien.", text: "Somos un estudio pequeño con experiencia grande: nos implicamos en los detalles porque sabemos que ahí vive la diferencia.", image: "/images/interior-sobre-nosotros.jpg" },
  contacto: { eyebrow: "Contacto", title: "Cuéntanos qué estás imaginando.", text: "Tanto si partes de una servilleta como si ya tienes un negocio en marcha, nos encantará escucharte.", image: "/images/interior-contacto.jpg" },
};

export function InteriorPage({ slug }: { slug: string }) { const copy = pageCopy[slug] ?? pageCopy.servicios; return <><ScrollProgress /><SiteHeader /><main><section className="grid min-h-[560px] bg-cream lg:grid-cols-2"><Reveal className="flex flex-col justify-center px-6 py-20 lg:px-20"><p className="eyebrow text-terracotta">{copy.eyebrow}</p><h1 className="display mt-6 max-w-[580px] text-5xl leading-[1.06] lg:text-7xl">{copy.title}</h1><p className="mt-7 max-w-[470px] text-sm leading-7 text-ink/65">{copy.text}</p><Magnetic strength={0.25} className="mt-8 w-fit"><Link href="/contacto" className="magnetic-btn group flex w-fit items-center gap-3 bg-olive px-6 py-4 text-[10px] font-semibold uppercase tracking-[.12em] text-white hover:bg-olive-deep">Hablemos <ArrowRight size={15} className="transition-transform duration-300 group-hover:translate-x-1" /></Link></Magnetic></Reveal><RevealImage src={copy.image} index={1} className="min-h-[360px]" /></section><section className="bg-olive px-6 py-20 text-cream lg:px-20"><div className="mx-auto max-w-[940px]"><Reveal><p className="eyebrow text-sand">Coffee Dreams Consulting</p><h2 className="display mt-5 text-4xl">Todo empieza con una conversación.</h2></Reveal>{slug === "contacto" ? <form className="mt-10 grid max-w-[680px] gap-5 sm:grid-cols-2" onSubmit={(event) => event.preventDefault()}>{["Nombre", "Email", "Tu negocio", "Cuéntanos tu proyecto"].map((label, index) => <label key={label} className={index === 3 ? "sm:col-span-2" : ""}><span className="mb-2 block text-[10px] font-semibold uppercase tracking-[.12em] text-sand">{label}</span>{index === 3 ? <textarea required rows={5} className="w-full border-b border-cream/35 bg-transparent p-2 text-sm outline-none transition-colors focus:border-sand" /> : <input required type={index === 1 ? "email" : "text"} className="w-full border-b border-cream/35 bg-transparent p-2 text-sm outline-none transition-colors focus:border-sand" />}</label>)}<Magnetic strength={0.2} className="w-fit sm:col-span-2"><button className="magnetic-btn group flex w-fit items-center gap-3 bg-olive-deep px-6 py-4 text-[10px] font-semibold uppercase tracking-[.12em] text-white transition-colors hover:bg-sand hover:text-ink">Enviar mensaje <ArrowRight size={15} className="transition-transform duration-300 group-hover:translate-x-1" /></button></Magnetic></form> : <div className="mt-10 grid gap-6 sm:grid-cols-3">{["Estrategia", "Experiencia", "Acompañamiento"].map((item, index) => <Reveal key={item} index={index} className="rounded-[18px] border border-cream/20 p-6 transition-colors duration-300 hover:border-sand/50"><Leaf size={21} className="text-sand" /><h3 className="display mt-8 text-2xl">{item}</h3><p className="mt-3 text-xs leading-6 text-cream/65">Pensamiento claro, sensibilidad por el detalle y acciones que se sostienen.</p></Reveal>)}</div>}</div></section></main><Footer /></>; }
