"use client";

import Link from "next/link";
import { useState } from "react";
import { Award, ArrowRight, BarChart3, BriefcaseBusiness, Camera, Check, Coffee, Compass, Globe, Leaf, Mail, MapPin, Menu, MessageCircle, PenLine, Phone, Sparkles, Users, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { BrandMark } from "@/components/brand-mark";
import NavigationMenuWithActiveItem from "@/components/ui/navigation-menu-05";

const nav = [["Inicio", "/", true], ["Servicios", "/servicios", false], ["Proyectos", "/proyectos", false], ["Formación", "/formacion", false], ["Recursos", "/recursos", false], ["Sobre nosotros", "/sobre-nosotros", false], ["Contacto", "/contacto", false]] as const;
const pillars = [
  { title: "Creamos", label: "Damos vida a tu proyecto", icon: Sparkles, image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=85", bullets: ["Concepto y viabilidad", "Diseño e identidad", "Carta y experiencia", "Operaciones y proveedores", "Apertura y acompañamiento"] },
  { title: "Analizamos", label: "Mejoramos tu negocio actual", icon: BarChart3, image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=85", bullets: ["Auditoría integral", "Análisis de producto y carta", "Costes y rentabilidad", "Procesos y eficiencia", "Experiencia del cliente"] },
  { title: "Formamos", label: "Desarrollamos tu equipo", icon: Users, image: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=900&q=85", bullets: ["Barista & Espresso", "Latte Art", "Métodos de filtrado", "Atención al cliente", "Formación a medida"] },
];
const steps = [["01", "Escuchamos", "Entendemos tu idea, tus necesidades y tus objetivos.", MessageCircle], ["02", "Analizamos", "Estudiamos el mercado, los números y el potencial.", Compass], ["03", "Diseñamos", "Creamos la estrategia, concepto y plan de acción.", PenLine], ["04", "Implementamos", "Te acompañamos en la puesta en marcha con nuestro equipo.", Coffee], ["05", "Mejoramos", "Medimos, optimizamos y crecemos juntos.", BarChart3]] as const;

function SiteHeader() {
  const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-50 border-b border-black/5 bg-cream/95 backdrop-blur-md"><div className="mx-auto flex h-[76px] max-w-[1320px] items-center justify-between px-6 lg:px-10"><Link href="/" className="flex items-center gap-3 leading-none" onClick={() => setOpen(false)}><BrandMark className="text-terracotta" size={34} /><span><span className="display block text-[22px]">Coffee Dreams<sup className="text-[8px]">®</sup></span><span className="ml-8 text-[10px] tracking-[.12em]">Consulting</span></span></Link><nav className="hidden items-center gap-5 lg:flex">{nav.map(([label, href, enabled]) => enabled ? <Link key={href} href={href} className="text-[9px] font-semibold uppercase tracking-[.08em] text-olive transition-colors hover:text-olive">{label}</Link> : <button key={href} type="button" className="text-[9px] font-semibold uppercase tracking-[.08em] text-ink/35 transition-colors hover:text-olive focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-terracotta">{label}</button>)}</nav><button type="button" className="hidden rounded-sm bg-ink/10 px-5 py-3 text-[9px] font-semibold uppercase tracking-[.12em] text-ink/40 transition-colors hover:bg-olive hover:text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-terracotta lg:block">Hablemos</button><button type="button" className="lg:hidden" onClick={() => setOpen(!open)} aria-label={open ? "Cerrar menú" : "Abrir menú"}>{open ? <X size={22} /> : <Menu size={22} />}</button></div>{open && <nav className="border-t border-black/5 bg-cream px-6 py-5 lg:hidden">{nav.map(([label, href, enabled]) => enabled ? <Link key={href} href={href} onClick={() => setOpen(false)} className="block border-b border-black/10 py-3 text-xs font-semibold uppercase tracking-[.12em] text-olive">{label}</Link> : <button key={href} type="button" className="block w-full border-b border-black/10 py-3 text-left text-xs font-semibold uppercase tracking-[.12em] text-ink/35 transition-colors hover:text-olive focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-terracotta">{label}</button>)}</nav>}</header>;
}

function NavigationHeader() {
  const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-50 border-b border-black/5 bg-cream/95 backdrop-blur-md"><div className="mx-auto flex h-[76px] max-w-[1320px] items-center justify-between px-6 lg:px-10"><Link href="/" className="flex items-center gap-3 leading-none" onClick={() => setOpen(false)}><BrandMark className="text-terracotta" size={34} /><span><span className="display block text-[22px]">Coffee Dreams<sup className="text-[8px]">®</sup></span><span className="ml-8 text-[10px] tracking-[.12em]">Consulting</span></span></Link><div className="hidden lg:block"><NavigationMenuWithActiveItem /></div><button type="button" className="hidden rounded-sm bg-ink/10 px-5 py-3 text-[9px] font-semibold uppercase tracking-[.12em] text-ink/40 transition-colors hover:bg-olive hover:text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-terracotta lg:block">Hablemos</button><button type="button" className="lg:hidden" onClick={() => setOpen(!open)} aria-label={open ? "Cerrar menú" : "Abrir menú"}>{open ? <X size={22} /> : <Menu size={22} />}</button></div>{open && <nav className="border-t border-black/5 bg-cream px-6 py-5 lg:hidden">{nav.map(([label, href, enabled]) => enabled ? <Link key={href} href={href} onClick={() => setOpen(false)} className="block border-b border-black/10 py-3 text-xs font-semibold uppercase tracking-[.12em] text-olive">{label}</Link> : <button key={href} type="button" className="block w-full border-b border-black/10 py-3 text-left text-xs font-semibold uppercase tracking-[.12em] text-ink/35 transition-colors hover:text-olive focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-terracotta">{label}</button>)}</nav>}</header>;
}

function Hero() { return <section className="relative overflow-hidden bg-cream"><div className="relative mx-auto grid max-w-[1320px] bg-none max-lg:bg-[url('/images/hero-cafe3.jpg')] max-lg:bg-cover max-lg:bg-[position:82%_70%] lg:min-h-[610px] lg:grid-cols-[.86fr_1.14fr] lg:bg-[url('/images/hero-cafe3.jpg')] lg:bg-[length:90%_auto] lg:bg-[position:right_70%] lg:bg-no-repeat lg:before:absolute lg:before:inset-y-0 lg:before:left-0 lg:before:z-[1] lg:before:w-[54%] lg:before:bg-gradient-to-r lg:before:from-cream lg:before:via-cream/95 lg:before:to-transparent lg:before:content-['']"><div className="relative z-10 flex flex-col justify-center max-lg:bg-gradient-to-b max-lg:from-cream/95 max-lg:via-cream/75 max-lg:to-cream/20 px-6 py-16 sm:px-10 lg:bg-transparent lg:px-14 lg:py-24"><p className="eyebrow mb-6 text-terracotta rise-in">Coffee Dreams Consulting</p><h1 className="display max-w-[600px] text-[42px] leading-[1.03] tracking-[-.025em] sm:text-[56px] lg:text-[64px] rise-in rise-delay-1">Creamos, analizamos y formamos para negocios de <em className="text-terracotta not-italic">café</em></h1><p className="mt-7 max-w-[410px] text-[13px] leading-7 text-ink/70 rise-in rise-delay-2">Te acompañamos en cada etapa de tu proyecto o negocio: desde la idea hasta la mejora continua. Más rentabilidad, mejor experiencia, mayor propósito.</p><Link href="/contacto" className="mt-8 inline-flex w-fit items-center gap-4 bg-terracotta px-6 py-4 text-[10px] font-semibold uppercase tracking-[.12em] text-white transition-colors hover:bg-terracotta/80">Cuéntanos tu proyecto <ArrowRight size={15} /></Link><p className="mt-9 flex items-center gap-2 text-[10px] text-olive"><Leaf size={18} /> Pasión por el café. Visión de negocio.</p></div><div className="relative max-lg:hidden min-h-[300px] overflow-hidden sm:min-h-[360px] lg:-ml-20 lg:block lg:min-h-full"><div className="absolute inset-0 hidden"/><div className="absolute inset-0 bg-gradient-to-r from-transparent via-transparent to-ink/10"/></div></div></section>; }

function Pillars() { return <section className="bg-cream"><div className="mx-auto max-w-[1320px] px-6 pb-16 pt-8 lg:px-10 lg:pt-10"><div className="mb-8 flex items-end justify-between"><div><p className="eyebrow text-terracotta">Lo que hacemos</p><h2 className="display mt-3 text-4xl">Tres formas de hacer crecer tu café.</h2></div><p className="hidden max-w-[250px] text-right text-xs leading-6 text-ink/60 md:block">Estrategia, creatividad y oficio para construir negocios con alma.</p></div><div className="grid overflow-hidden rounded-[22px] border border-black/10 md:grid-cols-3">{pillars.map(({ title, label, icon: Icon, bullets, image }, index) => <article key={title} className={`group relative min-h-[470px] overflow-hidden p-8 ${index === 1 ? "bg-olive text-cream" : "bg-sand/25"}`}><div className="absolute inset-0 bg-cover bg-center opacity-25 mix-blend-multiply transition duration-700 group-hover:scale-105 group-hover:opacity-35" style={{ backgroundImage: `url(${image})` }} /><div className="absolute inset-0 bg-gradient-to-t from-ink/15 via-transparent to-cream/10" /><div className="relative flex h-full flex-col"><div className="icon-badge mb-8 flex h-16 w-16 items-center justify-center rounded-full border-2 border-cream bg-cream text-olive"><Icon size={27} /></div><h3 className="display text-4xl">{title}</h3><p className="mt-2 text-xs font-semibold uppercase tracking-[.08em] text-terracotta">{label}</p><ul className="mt-8 space-y-3 text-[11px] leading-5 opacity-80">{bullets.map((bullet) => <li key={bullet} className="flex gap-2"><Check size={14} className="mt-0.5 shrink-0" />{bullet}</li>)}</ul><Link href="/servicios" className="mt-auto flex items-center gap-2 pt-8 text-[10px] font-semibold uppercase tracking-[.12em]">Saber más <ArrowRight size={14} /></Link></div></article>)}</div></div></section>; }

const stats: [string, string, LucideIcon][] = [["+15", "Años de experiencia", Award], ["+60", "Proyectos realizados", BarChart3], ["+200", "Profesionales formados", Users], ["100%", "Comprometidos", Coffee]];

function Stats() { return <section className="grain bg-olive-deep text-cream"><div className="mx-auto grid max-w-[1320px] items-center gap-10 px-6 py-14 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div><p className="eyebrow text-sand">La medida de nuestro trabajo</p><h2 className="display mt-4 text-4xl leading-tight">El café se disfruta.<br /><span className="text-sand">El negocio se diseña.</span></h2></div><div className="grid grid-cols-2 gap-y-8 sm:grid-cols-4">{stats.map(([number, label, Icon]) => <div key={label} className="border-l border-cream/20 pl-5"><Icon size={29} className="stat-icon mb-4 text-sand" aria-hidden="true" /><p className="display text-4xl text-sand">{number}</p><p className="mt-2 max-w-[110px] text-[9px] font-semibold uppercase leading-4 tracking-[.08em] text-cream/70">{label}</p></div>)}</div></div></section>; }

function Process() { return <section className="bg-cream px-6 py-20 lg:px-10"><div className="mx-auto max-w-[1150px]"><div className="text-center"><p className="eyebrow text-terracotta">Nuestro proceso</p><h2 className="display mt-3 text-4xl">Un camino claro hacia el éxito</h2></div><div className="relative mt-16 grid gap-10 md:grid-cols-5 md:gap-5">{steps.map(([number, title, text, Icon], index) => <div key={number} className="relative text-center"><div className="process-icon mx-auto flex h-[68px] w-[68px] items-center justify-center rounded-full border-2 border-terracotta/55 bg-cream text-olive"><Icon size={27} /></div><span className="mt-4 block text-[9px] font-semibold tracking-[.16em] text-terracotta">{number}</span><h3 className="mt-2 text-[11px] font-semibold uppercase tracking-[.08em]">{title}</h3><p className="mx-auto mt-3 max-w-[160px] text-[11px] leading-5 text-ink/60">{text}</p>{index < steps.length - 1 && <span className="absolute left-[calc(50%+42px)] right-[calc(-50%-42px)] top-8 hidden border-t border-dashed border-terracotta/35 md:block" />}</div>)}</div></div></section>; }

function Projects() { return <section className="grain bg-ink px-6 py-20 text-cream lg:px-10"><div className="mx-auto grid max-w-[1320px] gap-10 lg:grid-cols-[.95fr_1.05fr]"><div className="min-h-[420px] rounded-[20px] bg-[url('/images/idea.jpg')] bg-cover bg-center"/><div className="flex flex-col justify-center"><p className="eyebrow text-sand">Proyectos que inspiran</p><h2 className="display mt-4 max-w-[510px] text-5xl leading-[1.05]">Ideas que se convierten <span className="text-sand">en experiencias.</span></h2><p className="mt-6 max-w-[460px] text-sm leading-7 text-cream/65">Desde el concepto hasta la última taza, hacemos que cada detalle cuente. Una mirada estratégica con sensibilidad por lo que hace especial a un lugar.</p><Link href="/proyectos" className="mt-8 flex w-fit items-center gap-3 text-[10px] font-semibold uppercase tracking-[.13em] text-sand">Ver proyectos <ArrowRight size={15} /></Link><div className="mt-12 grid grid-cols-3 gap-3">{[["Diseño y apertura", "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=500&q=80"], ["Análisis y optimización", "https://images.unsplash.com/photo-1556740758-90de374c12ad?auto=format&fit=crop&w=500&q=80"], ["Formación", "/images/latteart.jpg"]].map(([label, image]) => <div key={label}><div className="aspect-square rounded-lg bg-cover bg-center" style={{ backgroundImage: `url(${image})` }} /><p className="mt-2 text-[9px] uppercase leading-4 tracking-[.08em] text-sand">{label}</p></div>)}</div></div></div></section>; }

function Trust() { return <section className="bg-cream px-6 py-12 lg:px-10"><div className="mx-auto max-w-[1320px]"><p className="eyebrow text-center text-terracotta">Con la confianza de</p><div className="mt-8 grid grid-cols-2 gap-8 text-center text-xl text-olive/80 sm:grid-cols-5"><span className="display">CAFÉ NORTE</span><span className="font-semibold tracking-[.14em]">MAMBÚ</span><span className="display font-semibold">TEMPO</span><span className="font-semibold tracking-[.14em]">QAPHI</span><span className="display font-semibold">HONEY</span></div></div></section>; }

function Newsletter() { return <section className="bg-sand px-6 py-16 lg:px-10"><div className="mx-auto flex max-w-[1050px] flex-col items-start justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow text-olive">Inspiración y recursos</p><h2 className="display mt-3 text-4xl">Ideas para hacer crecer<br />tu negocio de café.</h2></div><form className="flex w-full max-w-[390px] border-b border-ink/40 pb-2" onSubmit={(event) => event.preventDefault()}><label className="sr-only" htmlFor="newsletter">Tu email</label><input id="newsletter" type="email" placeholder="Tu email" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-ink/55" required /><button className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.12em]" type="submit">Suscribirme <ArrowRight size={14} /></button></form></div></section>; }

function Footer() { return <footer className="grain bg-olive-deep px-6 py-14 text-cream lg:px-10"><div className="mx-auto grid max-w-[1320px] gap-10 md:grid-cols-[1.4fr_.7fr_.9fr] md:gap-20"><div><Link href="/" className="flex items-center gap-3"><BrandMark className="text-terracotta" size={42} /><span className="display text-2xl">Coffee Dreams<sup className="text-[8px]">®</sup></span></Link><p className="mt-5 max-w-[260px] text-xs leading-6 text-cream/65">Consultoría, análisis y formación para negocios de café y hostelería.</p><p className="mt-8 text-[10px] uppercase tracking-[.1em] text-sand">Pasión por el café. Visión de negocio.</p><div className="mt-7 flex items-center gap-4"><a href="https://instagram.com" aria-label="Instagram" className="text-cream/70 transition-colors hover:text-terracotta"><Camera size={18} /></a><a href="https://linkedin.com" aria-label="LinkedIn" className="text-cream/70 transition-colors hover:text-terracotta"><BriefcaseBusiness size={18} /></a><a href="https://facebook.com" aria-label="Facebook" className="text-cream/70 transition-colors hover:text-terracotta"><Globe size={18} /></a></div></div><div><p className="eyebrow text-sand">Enlaces rápidos</p><div className="mt-5 grid gap-3 text-xs text-cream/70">{nav.slice(1, 6).map(([label, href]) => <Link key={href} href={href} className="transition-colors hover:text-sand">{label}</Link>)}</div></div><div><p className="eyebrow text-sand">Hablemos</p><div className="mt-5 grid gap-3 text-xs text-cream/70"><a className="flex items-center gap-2" href="mailto:hola@coffeedreams.es"><Mail size={15} /> hola@coffeedreams.es</a><a className="flex items-center gap-2" href="tel:+34961234567"><Phone size={15} /> +34 961 234 567</a><span className="flex items-center gap-2"><MapPin size={15} /> Alicante, España</span></div></div></div><div className="mx-auto mt-12 flex max-w-[1320px] items-center justify-between border-t border-cream/15 pt-5 text-[10px] text-cream/45"><span>© 2025 Coffee Dreams Consulting. Todos los derechos reservados.</span><BrandMark className="text-terracotta" size={30} label="" /></div></footer>; }

export function CoffeeDreamsHome() { return <><NavigationHeader /><main><Hero /><Pillars /><Stats /><Process /><Projects /><Trust /><Newsletter /></main><Footer /></>; }

const pageCopy: Record<string, { eyebrow: string; title: string; text: string; image: string }> = {
  servicios: { eyebrow: "Servicios", title: "Una mirada completa para un negocio con futuro.", text: "Aterrizamos conceptos, ordenamos operaciones y construimos experiencias de café que funcionan en el mundo real.", image: "https://images.unsplash.com/photo-1511081692775-05d0f180a065?auto=format&fit=crop&w=1400&q=85" },
  proyectos: { eyebrow: "Proyectos", title: "Lugares con identidad. Negocios con dirección.", text: "Una selección de aperturas, reposicionamientos y estrategias que convierten una buena idea en un lugar al que quieres volver.", image: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=1400&q=85" },
  formacion: { eyebrow: "Formación", title: "El equipo es el ingrediente que lo cambia todo.", text: "Programas prácticos para elevar la técnica, la hospitalidad y la confianza de las personas que están detrás de cada barra.", image: "https://images.unsplash.com/photo-1517231925375-bf2a727cce0b?auto=format&fit=crop&w=1400&q=85" },
  recursos: { eyebrow: "Recursos", title: "Ideas para mirar tu café con otros ojos.", text: "Notas, herramientas y conversaciones para tomar mejores decisiones y disfrutar más del camino.", image: "https://images.unsplash.com/photo-1453614512568-c4024d13c247?auto=format&fit=crop&w=1400&q=85" },
  "sobre-nosotros": { eyebrow: "Sobre nosotros", title: "Café, criterio y ganas de hacerlo bien.", text: "Somos un estudio pequeño con experiencia grande: nos implicamos en los detalles porque sabemos que ahí vive la diferencia.", image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1400&q=85" },
  contacto: { eyebrow: "Contacto", title: "Cuéntanos qué estás imaginando.", text: "Tanto si partes de una servilleta como si ya tienes un negocio en marcha, nos encantará escucharte.", image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1400&q=85" },
};

export function InteriorPage({ slug }: { slug: string }) { const copy = pageCopy[slug] ?? pageCopy.servicios; return <><SiteHeader /><main><section className="grid min-h-[560px] bg-cream lg:grid-cols-2"><div className="flex flex-col justify-center px-6 py-20 lg:px-20"><p className="eyebrow text-terracotta">{copy.eyebrow}</p><h1 className="display mt-6 max-w-[580px] text-5xl leading-[1.06] lg:text-7xl">{copy.title}</h1><p className="mt-7 max-w-[470px] text-sm leading-7 text-ink/65">{copy.text}</p><Link href="/contacto" className="mt-8 flex w-fit items-center gap-3 bg-olive px-6 py-4 text-[10px] font-semibold uppercase tracking-[.12em] text-white hover:bg-olive-deep">Hablemos <ArrowRight size={15} /></Link></div><div className="min-h-[360px] bg-cover bg-center" style={{ backgroundImage: `url(${copy.image})` }} /></section><section className="bg-olive px-6 py-20 text-cream lg:px-20"><div className="mx-auto max-w-[940px]"><p className="eyebrow text-sand">Coffee Dreams Consulting</p><h2 className="display mt-5 text-4xl">Todo empieza con una conversación.</h2>{slug === "contacto" ? <form className="mt-10 grid max-w-[680px] gap-5 sm:grid-cols-2" onSubmit={(event) => event.preventDefault()}>{["Nombre", "Email", "Tu negocio", "Cuéntanos tu proyecto"].map((label, index) => <label key={label} className={index === 3 ? "sm:col-span-2" : ""}><span className="mb-2 block text-[10px] font-semibold uppercase tracking-[.12em] text-sand">{label}</span>{index === 3 ? <textarea required rows={5} className="w-full border-b border-cream/35 bg-transparent p-2 text-sm outline-none focus:border-sand" /> : <input required type={index === 1 ? "email" : "text"} className="w-full border-b border-cream/35 bg-transparent p-2 text-sm outline-none focus:border-sand" />}</label>)}<button className="flex w-fit items-center gap-3 bg-olive-deep px-6 py-4 text-[10px] font-semibold uppercase tracking-[.12em] text-white hover:bg-sand hover:text-ink sm:col-span-2">Enviar mensaje <ArrowRight size={15} /></button></form> : <div className="mt-10 grid gap-6 sm:grid-cols-3">{["Estrategia", "Experiencia", "Acompañamiento"].map((item) => <div key={item} className="rounded-[18px] border border-cream/20 p-6"><Leaf size={21} className="text-sand" /><h3 className="display mt-8 text-2xl">{item}</h3><p className="mt-3 text-xs leading-6 text-cream/65">Pensamiento claro, sensibilidad por el detalle y acciones que se sostienen.</p></div>)}</div>}</div></section></main><Footer /></>; }
